/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import initCommandNamespace from './command_namespace';
import { PATHS, INDEX_WITH_TIME_1 } from './constants';
import { ADMIN_AUTH } from './commands';

initCommandNamespace(cy, 'core');

export const DEFAULT_OPTIONS = {
  workspace: {
    name: `wksp-${Date.now()}`,
    description: 'Workspace generated by Cypress',
    features: ['use-case-observability'],
  },
  dataSource: {
    title: `ds-${Date.now()}`,
    description: 'Data source added by Cypress',
    auth: { type: 'no_auth' },
    endpoint: PATHS.ENGINE,
    dataSourceVersion: '2.14.0',
    dataSourceEngineType: 'OpenSearch',
  },
  fixture: {
    mappingPath: `cypress/fixtures/query_enhancements/data_logs_1/${INDEX_WITH_TIME_1}.mapping.json`,
    dataPath: `cypress/fixtures/query_enhancements/data_logs_1/${INDEX_WITH_TIME_1}.data.ndjson`,
  },
  dataset: {
    title: INDEX_WITH_TIME_1,
    timeFieldName: 'timestamp',
    type: 'INDEX_PATTERN',
    fieldAttrs: '{}',
    fieldFormats: '{}',
    fields: JSON.stringify([
      {
        count: 0,
        name: 'category',
        type: 'string',
        esTypes: ['keyword'],
        scripted: false,
        searchable: true,
        aggregatable: true,
        readFromDocValues: true,
      },
      {
        count: 0,
        name: 'request_url',
        type: 'string',
        esTypes: ['keyword'],
        scripted: false,
        searchable: true,
        aggregatable: true,
        readFromDocValues: true,
      },
      {
        count: 0,
        name: 'service_endpoint',
        type: 'string',
        esTypes: ['keyword'],
        scripted: false,
        searchable: true,
        aggregatable: true,
        readFromDocValues: true,
      },
      {
        count: 0,
        name: 'status_code',
        type: 'number',
        esTypes: ['integer'],
        scripted: false,
        searchable: true,
        aggregatable: true,
        readFromDocValues: true,
      },
      {
        count: 0,
        name: 'timestamp',
        type: 'date',
        esTypes: ['date'],
        scripted: false,
        searchable: true,
        aggregatable: true,
        readFromDocValues: true,
      },
    ]),
  },
};

cy.core.add('createWorkspace', (options = {}) => {
  const { workspace } = { ...DEFAULT_OPTIONS, ...options };

  cy.request({
    method: 'POST',
    url: '/api/workspaces',
    headers: { 'osd-xsrf': true },
    body: {
      attributes: workspace,
    },
  }).then((resp) => {
    expect(resp.body.success).to.eq(true);
    const workspaceId = resp.body.result.id;
    cy.wrap(workspaceId).as('WORKSPACE_ID');
    return cy.wrap(workspaceId);
  });
});

cy.core.add('createDataSource', (options = {}) => {
  const { dataSource } = { ...DEFAULT_OPTIONS, ...options };

  return cy
    .request({
      method: 'POST',
      url: '/api/saved_objects/data-source',
      headers: {
        'osd-xsrf': true,
      },
      auth: ADMIN_AUTH,
      body: {
        attributes: dataSource,
      },
    })
    .then((resp) => {
      if (resp && resp.body && resp.body.id) {
        const dataSourceId = resp.body.id;
        cy.wrap(dataSourceId).as('DATA_SOURCE_ID');
        return cy.wrap(dataSourceId);
      }
    });
});

cy.core.add('associateDataSourcesToWorkspace', (workspaceId, dataSourceIds) => {
  const savedObjects = dataSourceIds.map((id) => ({ id, type: 'data-source' }));

  cy.request({
    method: 'POST',
    url: `/w/${workspaceId}/api/workspaces/_associate`,
    headers: { 'osd-xsrf': true },
    body: {
      savedObjects,
      workspaceId,
    },
  }).then((resp) => {
    expect(resp.body.success).to.eq(true);
    return cy.wrap(resp);
  });
});

cy.core.add('createDataset', (workspaceId, dataSourceId, options = {}) => {
  const { dataset } = {
    ...DEFAULT_OPTIONS,
    ...options,
  };

  cy.log(`Creating dataset: { title: ${dataset.title}, type: ${dataset.type} }: `);

  return cy
    .request({
      method: 'POST',
      url: `/w/${workspaceId}/api/saved_objects/index-pattern`,
      headers: {
        'osd-xsrf': 'osd-fetch',
      },
      body: {
        attributes: {
          ...dataset,
          type: undefined,
        },
        references: [{ name: 'dataSource', type: 'data-source', id: dataSourceId }],
        workspaces: [workspaceId],
      },
    })
    .then((resp) => {
      expect(resp.status).to.eq(200);
      const datasetId = resp.body.id;
      cy.wrap(datasetId).as('DATASET_ID');
      return cy.wrap(datasetId);
    });
});

cy.core.add('setUiSettings', (workspaceId, changes = {}) => {
  return cy
    .request({
      method: 'POST',
      url: `/w/${workspaceId}/api/opensearch-dashboards/settings`,
      headers: {
        'osd-xsrf': 'osd-fetch',
      },
      body: {
        changes,
      },
    })
    .then((resp) => {
      expect(resp.status).to.eq(200);
      return cy.wrap(resp);
    });
});

cy.core.add('setupTestResources', (options = {}) => {
  const {
    dataSource: { endpoint },
    fixture: { mappingPath, dataPath },
    dataset,
  } = {
    ...DEFAULT_OPTIONS,
    ...options,
  };

  cy.log(
    `Setting up resources: { endpoint: ${endpoint}, mappingPath: ${mappingPath}, dataPath: ${dataPath} }`
  );

  return cy.osd.setupTestData(endpoint, [mappingPath], [dataPath]).then(() =>
    cy.core.createDataSource().then((dataSourceId) => {
      return cy.core.createWorkspace().then((workspaceId) => {
        cy.core.setUiSettings(workspaceId, {
          defaultWorkspace: workspaceId,
          defaultDataSource: dataSourceId,
        });
        cy.core.associateDataSourcesToWorkspace(workspaceId, [dataSourceId]);
        return cy.core.createDataset(workspaceId, dataSourceId, { dataset }).then((datasetId) => {
          cy.core.setUiSettings(workspaceId, {
            defaultIndex: datasetId,
          });
          cy.log(
            `Resources created: { workspaceId: ${workspaceId}, dataSourceId: ${dataSourceId}, datasetId: ${datasetId} }`
          );
          return cy.wrap({
            workspaceId,
            dataSourceId,
            datasetId,
          });
        });
      });
    })
  );
});

cy.core.add('cleanupTestResources', (options = {}) => {
  const { index = DEFAULT_OPTIONS.dataset.title, workspaceId, dataSourceId, datasetId } = options;

  cy.log(
    `Cleaning up resources: { workspaceId: ${workspaceId}, dataSourceId: ${dataSourceId}, datasetId: ${datasetId} }`
  );

  cy.request({
    method: 'DELETE',
    url: `/api/workspaces/${workspaceId}`,
    headers: { 'osd-xsrf': true },
    failOnStatusCode: false,
  });

  cy.request({
    method: 'DELETE',
    url: `/api/saved_objects/data-source/${dataSourceId}?force=true`,
    headers: { 'osd-xsrf': true },
    failOnStatusCode: false,
  });

  cy.request({
    method: 'DELETE',
    url: `/api/saved_objects/index-pattern/${datasetId}?force=true`,
    headers: { 'osd-xsrf': true },
    failOnStatusCode: false,
  });

  cy.osd.deleteIndex(index);

  cy.clearLocalStorage();
});
